version: 2
jobs:
  test:
    docker: 
      - image: rishabhpoddar/android-node-mysql-git
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run: (cd / && ./runMySQL.sh)
      - run: mysql -u root --password=root -e "CREATE DATABASE auth_session;"
      - run: mysql -u root --password=root -e "set global max_connections = 10000;"
      - checkout
      - run: cd supertokens-android/backend/ && npm i -d && ./node_modules/.bin/tsc -p tsconfig.json
      - run: cd supertokens-android/backend/ && TEST_MODE=testing node build/index.js &
      - run: cd supertokens-android/ && ./gradlew test

workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - dev
                - master