version: 2
jobs:
  publish:
    docker:
      - image: rishabhpoddar/android-node-mysql-git
    steps:
      - run: (cd / && ./runMySQL.sh)
      - run: mysql -u root --password=root -e "CREATE DATABASE auth_session;"
      - run: mysql -u root --password=root -e "set global max_connections = 10000;"
      - checkout
      - run: cd backend/ && npm i -d && ./node_modules/.bin/tsc -p tsconfig.json
      - run: 
          command: cd backend/ && TEST_MODE=testing node build/index.js
          background: true
      - run: ./gradlew clean build bintrayUpload -PbintrayUser=supertokens -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  test:
    docker: 
      - image: rishabhpoddar/android-node-mysql-git
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: (cd / && ./runMySQL.sh)
      - run: mysql -u root --password=root -e "CREATE DATABASE auth_session;"
      - run: mysql -u root --password=root -e "set global max_connections = 10000;"
      - run: apt-get install -y jq
      - run: (cd .circleci/ && ./doTests.sh)

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            branches:
              only:
                - "0.2"